-- Run this entire file in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  name text unique not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_reports (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id),
  work_date date not null,
  status text not null default 'draft' check (status in ('draft','submitted')),
  notes text not null default '',
  entered_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, work_date)
);

create table if not exists public.hourly_entries (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.daily_reports(id) on delete cascade,
  role text not null,
  quantity integer not null default 0 check (quantity >= 0)
);

create table if not exists public.subcontractor_entries (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.daily_reports(id) on delete cascade,
  subcontractor_name text not null,
  trade text not null default '',
  quantity integer not null default 0 check (quantity >= 0)
);

insert into public.projects(name) values
('Sky Living - Surry'),('Sony Tower'),('Prior St - Vancouver'),('CCNE - Surry - Blue City'),('10th & Discovery - Vancouver'),('Uptown Phase 4'),('1045 Burnaby'),('Poor Italian')
on conflict (name) do nothing;

alter table public.projects enable row level security;
alter table public.daily_reports enable row level security;
alter table public.hourly_entries enable row level security;
alter table public.subcontractor_entries enable row level security;

-- Authenticated users can use the tracker. Tighten these policies later with project assignments.
create policy "projects readable" on public.projects for select to authenticated using (true);
create policy "reports readable" on public.daily_reports for select to authenticated using (true);
create policy "reports insertable" on public.daily_reports for insert to authenticated with check ((select auth.uid()) = entered_by);
create policy "reports editable" on public.daily_reports for update to authenticated using (true) with check (true);
create policy "hourly readable" on public.hourly_entries for select to authenticated using (true);
create policy "hourly writable" on public.hourly_entries for all to authenticated using (true) with check (true);
create policy "subs readable" on public.subcontractor_entries for select to authenticated using (true);
create policy "subs writable" on public.subcontractor_entries for all to authenticated using (true) with check (true);

create or replace view public.daily_reports_view as
select
  r.id,
  p.name as project_name,
  r.work_date,
  case when r.status = 'submitted' then 'Submitted' else 'Draft' end as status,
  r.notes,
  r.created_at,
  r.updated_at,
  coalesce((select jsonb_object_agg(h.role, h.quantity) from public.hourly_entries h where h.report_id = r.id), '{}'::jsonb) as hourly,
  coalesce((select jsonb_agg(jsonb_build_object('id', s.id::text, 'subcontractor', s.subcontractor_name, 'trade', s.trade, 'quantity', s.quantity)) from public.subcontractor_entries s where s.report_id = r.id), '[]'::jsonb) as subcontractors
from public.daily_reports r
join public.projects p on p.id = r.project_id;

grant select on public.daily_reports_view to authenticated;
